### create user
POST http://localhost:5000/api/users
Content-Type: application/json

{
    "username": "kattlover",
    "email": "blaha@blala.com",
    "password": "1234"
}

 
### get all users
GET http://localhost:5000/api/users


### get specific user by ID
GET http://localhost:5000/api/users/626131c60f73aed532762dc6

###  delete specific user by ID

DELETE http://localhost:5000/api/users/626131c60f73aed532762dc6