import Layout from '../components/Layout';

function AdminPage() {
  return (
    <p>
      lolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasddlolasdd
    </p>
  );
}

export default AdminPage;
